import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json([
    {
      title: "Detox da Alma",
      description: "Este evento irá abordar os desafios e oportunidades de se mudar para uma cidade grande. Participe para aprender e compartilhar experiências!",
      category: "Podcast",
      image: "/images/chindinma.png",
    },
    {
      title: "Melhores suportando mulheres",
      description: "Descubra maneiras práticas de exercer a solidariedade em sua comunidade neste evento especial.",
      category: "Solidariedade",
      image: "/images/workshopmulheres.png",
    },
    {
      title: "Testemunhos no Podfé",
      description: "Um bate-papo inspirador sobre fé, transformação e crescimento pessoal em sua comunidade neste evento especial.",
      category: "Podcast",
      image: "/images/Cantoraovivo.png",
    },
    {
      title: "Encontro de Mulheres de Fé",
      description: "Um evento especial para mulheres que buscam fortalecer sua fé e construir relacionamentos significativos em comunidade.",
      category: "Encontro",
      image: "/images/workshopmulheres.png",
    },
    {
      title: "Conferência de Jovens",
      description: "Um evento dinâmico para jovens que desejam crescer na fé e desenvolver seus dons e talentos.",
      category: "Conferência",
      image: "/images/conf-1.jpg",
    },
    {
      title: "Workshop de Liderança",
      description: "Aprenda princípios bíblicos de liderança e como aplicar em sua vida pessoal e profissional.",
      category: "Workshop",
      image: "/images/conf-3.jpg",
    },
    {
      title: "Culto de Adoração",
      description: "Venha participar de um momento especial de adoração e louvor com a comunidade Podfé.",
      category: "Culto",
      image: "/images/prayers.jpg",
    },
    {
      title: "Retiro Espiritual",
      description: "Um fim de semana dedicado ao fortalecimento espiritual e renovação da fé.",
      category: "Retiro",
      image: "/images/conf.jpg",
    },
    {
      title: "Seminário de Casamento",
      description: "Um evento especial para casais que desejam fortalecer seu relacionamento baseado em princípios bíblicos.",
      category: "Seminário",
      image: "/images/TudosobreCasamento.png",
    },
    {
      title: "Encontro de Homens",
      description: "Um espaço para homens compartilharem experiências e crescerem juntos na fé.",
      category: "Encontro",
      image: "/images/ProfetaCastelo.png",
    },
    {
      title: "Workshop de Música",
      description: "Aprenda técnicas de música e adoração para servir melhor na igreja e na comunidade.",
      category: "Workshop",
      image: "/images/Cantoraovivo.png",
    },
    {
      title: "Conferência de Família",
      description: "Um evento completo para toda a família, com atividades para crianças, jovens e adultos.",
      category: "Conferência",
      image: "/images/piquenique.jpeg",
    },
    {
      title: "Encontro de Oração",
      description: "Uma noite especial de oração e intercessão pela cidade e pela nação.",
      category: "Oração",
      image: "/images/prayers.jpg",
    },
    {
      title: "Workshop de Evangelismo",
      description: "Aprenda técnicas e estratégias para compartilhar o evangelho de forma efetiva.",
      category: "Workshop",
      image: "/images/conf-1.jpg",
    },
    {
      title: "Conferência de Mulheres",
      description: "Um evento especial para mulheres de todas as idades, com palestras, workshops e networking.",
      category: "Conferência",
      image: "/images/workshopmulheres.png",
    },
    {
      title: "Encontro de Adolescentes",
      description: "Um espaço divertido e seguro para adolescentes crescerem na fé e fazerem novos amigos.",
      category: "Encontro",
      image: "/images/student.jpeg",
    },
    {
      title: "Workshop de Finanças",
      description: "Aprenda princípios bíblicos de administração financeira e como aplicar em sua vida.",
      category: "Workshop",
      image: "/images/conf-3.jpg",
    },
    {
      title: "Culto de Celebração",
      description: "Uma celebração especial com música, dança e testemunhos de transformação.",
      category: "Culto",
      image: "/images/Cantoraovivo.png",
    },
    {
      title: "Seminário de Paternidade",
      description: "Um evento para pais e mães aprenderem princípios bíblicos de criação de filhos.",
      category: "Seminário",
      image: "/images/TudosobreCasamento.png",
    },
    {
      title: "Encontro de Idosos",
      description: "Um momento especial para a terceira idade compartilhar experiências e sabedoria.",
      category: "Encontro",
      image: "/images/ProfetaCastelo.png",
    },
    {
      title: "Workshop de Comunicação",
      description: "Aprenda técnicas de comunicação eficaz baseadas em princípios cristãos.",
      category: "Workshop",
      image: "/images/conf-1.jpg",
    },
    {
      title: "Conferência de Missões",
      description: "Um evento para despertar o coração missionário e conhecer projetos missionários.",
      category: "Conferência",
      image: "/images/conf.jpg",
    },
    {
      title: "Encontro de Crianças",
      description: "Um evento divertido e educativo para crianças aprenderem sobre Deus de forma lúdica.",
      category: "Encontro",
      image: "/images/piquenique.jpeg",
    },
    {
      title: "Workshop de Relacionamentos",
      description: "Aprenda como construir relacionamentos saudáveis baseados em princípios bíblicos.",
      category: "Workshop",
      image: "/images/TudosobreCasamento.png",
    },
    {
      title: "Culto de Gratidão",
      description: "Um momento especial para agradecer pelas bênçãos recebidas durante o ano.",
      category: "Culto",
      image: "/images/prayers.jpg",
    },
    {
      title: "Seminário de Carreira",
      description: "Aprenda como alinhar sua carreira profissional com seus valores cristãos.",
      category: "Seminário",
      image: "/images/conf-3.jpg",
    },
    {
      title: "Encontro de Casais",
      description: "Um evento especial para casais fortalecerem seu relacionamento e crescerem juntos.",
      category: "Encontro",
      image: "/images/TudosobreCasamento.png",
    },
    {
      title: "Workshop de Saúde",
      description: "Aprenda princípios bíblicos para uma vida saudável em corpo, alma e espírito.",
      category: "Workshop",
      image: "/images/workshopmulheres.png",
    },
    {
      title: "Conferência de Jovens Profissionais",
      description: "Um evento para jovens profissionais conectarem fé e carreira de forma prática.",
      category: "Conferência",
      image: "/images/student.jpeg",
    },
    {
      title: "Encontro de Mães",
      description: "Um espaço especial para mães compartilharem experiências e receberem apoio.",
      category: "Encontro",
      image: "/images/workshopmulheres.png",
    },
    {
      title: "Workshop de Tecnologia",
      description: "Aprenda como usar a tecnologia para glorificar a Deus e servir à comunidade.",
      category: "Workshop",
      image: "/images/conf-1.jpg",
    },
    {
      title: "Culto de Avivamento",
      description: "Um momento de renovação espiritual e despertamento para a igreja.",
      category: "Culto",
      image: "/images/Cantoraovivo.png",
    },
    {
      title: "Seminário de Empreendedorismo",
      description: "Aprenda princípios bíblicos para empreender com propósito e excelência.",
      category: "Seminário",
      image: "/images/conf-3.jpg",
    },
    {
      title: "Encontro de Pais Solteiros",
      description: "Um espaço de apoio e encorajamento para pais que estão criando filhos sozinhos.",
      category: "Encontro",
      image: "/images/ProfetaCastelo.png",
    },
    {
      title: "Workshop de Arte",
      description: "Aprenda como usar seus dons artísticos para glorificar a Deus e abençoar outros.",
      category: "Workshop",
      image: "/images/Cantoraovivo.png",
    },
    {
      title: "Conferência de Liderança",
      description: "Um evento para líderes desenvolverem suas habilidades e crescerem na fé.",
      category: "Conferência",
      image: "/images/conf.jpg",
    },
    {
      title: "Encontro de Adolescentes",
      description: "Um espaço divertido e seguro para adolescentes crescerem na fé e fazerem novos amigos.",
      category: "Encontro",
      image: "/images/student.jpeg",
    },
    {
      title: "Workshop de Comunicação",
      description: "Aprenda técnicas de comunicação eficaz baseadas em princípios cristãos.",
      category: "Workshop",
      image: "/images/conf-1.jpg",
    },
    {
      title: "Culto de Celebração",
      description: "Uma celebração especial com música, dança e testemunhos de transformação.",
      category: "Culto",
      image: "/images/Cantoraovivo.png",
    },
  ]);
} 